////////////////////////////////////////////////////////////////////////////////
/// UiKeyboard.h

#pragma once
#include "BtTypes.h"

enum UiKeyCode
{
	UiKeyCode_ESCAPE          =0x01,
	UiKeyCode_1               =0x02,
	UiKeyCode_2               =0x03,
	UiKeyCode_3               =0x04,
	UiKeyCode_4               =0x05,
	UiKeyCode_5               =0x06,
	UiKeyCode_6               =0x07,
	UiKeyCode_7               =0x08,
	UiKeyCode_8               =0x09,
	UiKeyCode_9               =0x0A,
	UiKeyCode_0               =0x0B,
	UiKeyCode_MINUS           =0x0C,
	UiKeyCode_EQUALS          =0x0D,
	UiKeyCode_PLUS		      =0x0D,
	UiKeyCode_BACK            =0x0E,
	UiKeyCode_TAB             =0x0F,
	UiKeyCode_Q               =0x10,
	UiKeyCode_W               =0x11,
	UiKeyCode_E               =0x12,
	UiKeyCode_R               =0x13,
	UiKeyCode_T               =0x14,
	UiKeyCode_Y               =0x15,
	UiKeyCode_U               =0x16,
	UiKeyCode_I               =0x17,
	UiKeyCode_O               =0x18,
	UiKeyCode_P               =0x19,
	UiKeyCode_LBRACKET        =0x1A,
	UiKeyCode_RBRACKET        =0x1B,
	UiKeyCode_RETURN          =0x1C,
	UiKeyCode_LCONTROL        =0x1D,
	UiKeyCode_A               =0x1E,
	UiKeyCode_S               =0x1F,
	UiKeyCode_D               =0x20,
	UiKeyCode_F               =0x21,
	UiKeyCode_G               =0x22,
	UiKeyCode_H               =0x23,
	UiKeyCode_J               =0x24,
	UiKeyCode_K               =0x25,
	UiKeyCode_L               =0x26,
	UiKeyCode_SEMICOLON       =0x27,
	UiKeyCode_APOSTROPHE      =0x28,
	UiKeyCode_GRAVE           =0x29,
	UiKeyCode_LSHIFT          =0x2A,
	UiKeyCode_BACKSLASH       =0x2B,
	UiKeyCode_Z               =0x2C,
	UiKeyCode_X               =0x2D,
	UiKeyCode_C               =0x2E,
	UiKeyCode_V               =0x2F,
	UiKeyCode_B               =0x30,
	UiKeyCode_N               =0x31,
	UiKeyCode_M               =0x32,
	UiKeyCode_COMMA           =0x33,
	UiKeyCode_PERIOD          =0x34,
	UiKeyCode_SLASH           =0x35,
	UiKeyCode_RSHIFT          =0x36,
	UiKeyCode_MULTIPLY        =0x37,
	UiKeyCode_LMENU           =0x38,
	UiKeyCode_SPACE           =0x39,
	UiKeyCode_CAPITAL         =0x3A,
	UiKeyCode_F1              =0x3B,
	UiKeyCode_F2              =0x3C,
	UiKeyCode_F3              =0x3D,
	UiKeyCode_F4              =0x3E,
	UiKeyCode_F5              =0x3F,
	UiKeyCode_F6              =0x40,
	UiKeyCode_F7              =0x41,
	UiKeyCode_F8              =0x42,
	UiKeyCode_F9              =0x43,
	UiKeyCode_F10             =0x44,
	UiKeyCode_NUMLOCK         =0x45,
	UiKeyCode_SCROLL          =0x46,
	UiKeyCode_NUMPAD7         =0x47,
	UiKeyCode_NUMPAD8         =0x48,
	UiKeyCode_NUMPAD9         =0x49,
	UiKeyCode_SUBTRACT        =0x4A,
	UiKeyCode_NUMPAD4         =0x4B,
	UiKeyCode_NUMPAD5         =0x4C,
	UiKeyCode_NUMPAD6         =0x4D,
	UiKeyCode_ADD             =0x4E,
	UiKeyCode_NUMPAD1         =0x4F,
	UiKeyCode_NUMPAD2         =0x50,
	UiKeyCode_NUMPAD3         =0x51,
	UiKeyCode_NUMPAD0         =0x52,
	UiKeyCode_DECIMAL         =0x53,
	UiKeyCode_OEM_102         =0x56,
	UiKeyCode_F11             =0x57,
	UiKeyCode_F12             =0x58,
	UiKeyCode_F13             =0x64,
	UiKeyCode_F14             =0x65,
	UiKeyCode_F15             =0x66,
	UiKeyCode_KANA            =0x70,
	UiKeyCode_ABNT_C1         =0x73,
	UiKeyCode_CONVERT         =0x79,
	UiKeyCode_NOCONVERT       =0x7B,
	UiKeyCode_YEN             =0x7D,
	UiKeyCode_ABNT_C2         =0x7E,
	UiKeyCode_NUMPADEQUALS    =0x8D,
	UiKeyCode_PREVTRACK       =0x90,
	UiKeyCode_AT              =0x91,
	UiKeyCode_COLON           =0x92,
	UiKeyCode_UNDERLINE       =0x93,
	UiKeyCode_KANJI           =0x94,
	UiKeyCode_STOP            =0x95,
	UiKeyCode_AX              =0x96,
	UiKeyCode_UNLABELED       =0x97,
	UiKeyCode_NEXTTRACK       =0x99,
	UiKeyCode_NUMPADENTER     =0x9C,
	UiKeyCode_RCONTROL        =0x9D,
	UiKeyCode_MUTE            =0xA0,
	UiKeyCode_CALCULATOR      =0xA1,
	UiKeyCode_PLAYPAUSE       =0xA2,
	UiKeyCode_MEDIASTOP       =0xA4,
	UiKeyCode_VOLUMEDOWN      =0xAE,
	UiKeyCode_VOLUMEUP        =0xB0,
	UiKeyCode_WEBHOME         =0xB2,
	UiKeyCode_NUMPADCOMMA     =0xB3,
	UiKeyCode_DIVIDE          =0xB5,
	UiKeyCode_SYSRQ           =0xB7,
	UiKeyCode_RMENU           =0xB8,
	UiKeyCode_PAUSE           =0xC5,
	UiKeyCode_HOME            =0xC7,
	UiKeyCode_UP              =0xC8,
	UiKeyCode_PRIOR           =0xC9,
	UiKeyCode_LEFT            =0xCB,
	UiKeyCode_RIGHT           =0xCD,
	UiKeyCode_END             =0xCF,
	UiKeyCode_DOWN            =0xD0,
	UiKeyCode_NEXT            =0xD1,
	UiKeyCode_INSERT          =0xD2,
	UiKeyCode_DELETE          =0xD3,
	UiKeyCode_LWIN            =0xDB,
	UiKeyCode_RWIN            =0xDC,
	UiKeyCode_APPS            =0xDD,
	UiKeyCode_POWER           =0xDE,
	UiKeyCode_SLEEP           =0xDF,
	UiKeyCode_WAKE            =0xE3,
	UiKeyCode_WEBSEARCH       =0xE5,
	UiKeyCode_WEBFAVORITES    =0xE6,
	UiKeyCode_WEBREFRESH      =0xE7,
	UiKeyCode_WEBSTOP         =0xE8,
	UiKeyCode_WEBFORWARD      =0xE9,
	UiKeyCode_WEBBACK         =0xEA,
	UiKeyCode_MYCOMPUTER      =0xEB,
	UiKeyCode_MAIL            =0xEC,
	UiKeyCode_MEDIASELECT     =0xED,
	UiKeyCode_ALT			  =0xEE,
    UiKeyCode_MAX             =0xFF
};

// Class Declaration
class UiKeyboard
{
public:

	// Instance
	static UiKeyboard  		   *pInstance();

	// Accessors
	virtual BtBool 				IsHeld( UiKeyCode character ) = 0;
	virtual BtBool 				IsPressed( UiKeyCode character ) = 0;
	virtual BtBool 				IsReleased( UiKeyCode character ) = 0;
	virtual BtBool				IsPressed () = 0;

protected:

	static UiKeyboard		   *m_pInstance;
	BtBool						m_debugButtons;
};
